sudo: required
services:
  - docker

language: erlang
otp_release:
  - 20.0

install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
before_script:
  - ./startOrientdb.sh
script:
  - rebar3 eunit
  - rebar3 ct
  - rebar3 dialyzer
